# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :first_lane do
	get_ipa_info_plist_value(ipa: "testty.ipa", key: "CFBundleVersion")
    # add actions here: https://docs.fastlane.tools/actions
  end

lane :update_localization do
	sh("git submodule update --remote --recursive")
	echo(message: "Hi")
	build_number = get_build_number(xcodeproj: "testty.xcodeproj")
	echo(message: build_number)
	increment_version_number(bump_type: "minor")
	version = get_version_number(xcodeproj: "testty.xcodeproj")
	echo(message: version)
end

lane :tests do
  run_tests(scheme: "testty")
end

  lane :bsim do
    xcodebuild(
        archive: true,
        archive_path: "./testty/testty.xcarchive",
        scheme: "testty",
        destination: "platform=iOS Simulator,name=iPhone 7",
        workspace: "testty.xcworkspace"
    )
   end
end
